version: '3'

services:
  flask_app:
    container_name: flask_app
    build: .
    command: flask --app main run --host=0.0.0.0
    ports:
      - 5000:5000
    depends_on:
      - rabbitmq
  rabbitmq:
    image: "rabbitmq:3-management"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  rabbitmq_data:

