version: '3'

networks:
  ecommerce_network:
    driver: bridge
    external: true

services:
  flask_app:
    container_name: flask_app
    build: .
    restart: always
    command: python main.py
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
    ports:
      - 5000:5000
    volumes:
      - .:/app
    networks:
      - ecommerce_network

  test:
    container_name: test
    build: .
    restart: "no"
    command: python -m unittest
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
    ports:
      - "5678:5678"
    volumes:
      - .:/app
    networks:
      - ecommerce_network